services:
  - type: web
    name: ecommerce-store-app
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: DB_URL
        fromDatabase:
          name: ecommerce-store-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: ecommerce-store-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: ecommerce-store-db
          property: password

databases:
  - name: ecommerce-store-db
    plan: free
    databaseName: ecommerce_store
    user: ecommerce_user
