-- Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    mobile VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    pin_code VARCHAR(255),
    password VARCHAR(255),
    profile_image VARCHAR(255),
    role VARCHAR(255),
    is_enable BOOLEAN,
    account_status_non_locked BOOLEAN,
    account_failed_attempt_count INTEGER,
    account_lock_time TIMESTAMP WITHOUT TIME ZONE,
    reset_tokens VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- Create categories table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR(255) NOT NULL,
    category_image VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (category_name)
);

-- Create products table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_title VARCHAR(255),
    product_description TEXT,
    product_category VARCHAR(255),
    product_price DOUBLE PRECISION,
    product_stock INTEGER DEFAULT 0,
    product_image VARCHAR(255),
    discount INTEGER DEFAULT 0,
    discount_price DOUBLE PRECISION,
    is_active BOOLEAN DEFAULT TRUE,
    quantity INTEGER DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

-- Create carts table with foreign keys to users and products
CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quantity INTEGER,
    user_id BIGINT,
    product_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_carts_product FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Create order_addresses table
CREATE TABLE order_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    mobile VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    pin_code VARCHAR(255),
    PRIMARY KEY (id)
);

-- Create product_orders table with foreign keys
CREATE TABLE product_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id VARCHAR(255),
    order_date TIMESTAMP WITHOUT TIME ZONE,
    price DOUBLE PRECISION,
    quantity INTEGER,
    status VARCHAR(255),
    payment_type VARCHAR(255),
    user_id BIGINT,
    product_id BIGINT,
    order_address_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_product_orders_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_product_orders_address FOREIGN KEY (order_address_id) REFERENCES order_addresses(id)
);