-- ============================================
-- Create Database
-- ============================================
CREATE DATABASE ecommerce_demo;

-- Switch to DB
\c ecommerce_demo;

-- ============================================
-- USERS & ROLES
-- ============================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    mobile VARCHAR(50),
    address VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    pin_code VARCHAR(20),
    profile_image VARCHAR(255),
    role VARCHAR(50),
    is_enable BOOLEAN DEFAULT TRUE,
    account_status_non_locked BOOLEAN DEFAULT TRUE,
    account_failed_attempt_count INTEGER DEFAULT 0,
    account_lock_time TIMESTAMP WITHOUT TIME ZONE,
    reset_tokens VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE
);

-- ============================================
-- CATEGORIES
-- ============================================
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    category_image VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_categories_name UNIQUE (category_name)
);

-- ============================================
-- PRODUCTS
-- ============================================
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_title VARCHAR(255) NOT NULL,
    product_description TEXT,
    product_category VARCHAR(255),
    product_price NUMERIC(10,2) NOT NULL,
    product_stock INTEGER DEFAULT 0,
    product_image VARCHAR(255),
    discount INTEGER DEFAULT 0,
    discount_price NUMERIC(10,2),
    is_active BOOLEAN DEFAULT TRUE,
    quantity INTEGER DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- CARTS
-- ============================================
CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE
);

-- ============================================
-- ORDER ADDRESSES
-- ============================================
CREATE TABLE order_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    mobile VARCHAR(50),
    address VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    pin_code VARCHAR(20)
);

-- ============================================
-- ORDERS
-- ============================================
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    total_amount NUMERIC(10,2),
    status VARCHAR(20),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- ORDER ITEMS
-- ============================================
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INT NOT NULL,
    price NUMERIC(10,2) NOT NULL
);

-- ============================================
-- PRODUCT ORDERS (detailed tracking)
-- ============================================
CREATE TABLE product_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(255) NOT NULL,
    order_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    price NUMERIC(10,2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(255),
    payment_type VARCHAR(255),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    order_address_id BIGINT REFERENCES order_addresses(id) ON DELETE SET NULL
);

-- ============================================
-- DEFAULT DATA
-- ============================================

-- Insert Roles
INSERT INTO roles (name) VALUES 
('ROLE_ADMIN'),
('ROLE_CUSTOMER');

-- Insert Admin User (bcrypt hash of "admin123")
INSERT INTO users (username, email, password)
VALUES ('admin', 'admin@example.com', '$2a$10$w7h7mF0x9m1iS7G0yDeQwOb7iH4tX2v0xgqf0o2kY1lF9bV8g2y3e');

-- Assign ROLE_ADMIN to Admin
INSERT INTO user_roles (user_id, role_id)
VALUES ((SELECT id FROM users WHERE username = 'admin'), (SELECT id FROM roles WHERE name = 'ROLE_ADMIN'));

-- Sample Products
INSERT INTO products (product_title, product_description, product_category, product_price, discount, quantity, product_image)
VALUES
('Smartphone', 'Latest 5G smartphone with 128GB storage', 'Electronics', 29999.00, 10, 50, 'https://example.com/images/smartphone.jpg'),
('Laptop', 'Powerful laptop with Intel i7 processor', 'Electronics', 65999.00, 15, 30, 'https://example.com/images/laptop.jpg'),
('T-Shirt', '100% cotton round neck T-shirt', 'Clothing', 599.00, 5, 100, 'https://example.com/images/tshirt.jpg'),
('Jeans', 'Slim fit blue denim jeans', 'Clothing', 1499.00, 20, 60, 'https://example.com/images/jeans.jpg'),
('Novel', 'Bestselling fiction novel', 'Books', 399.00, 0, 200, 'https://example.com/images/novel.jpg'),
('Study Table', 'Wooden study table with storage', 'Furniture', 4999.00, 10, 20, 'https://example.com/images/table.jpg'),
('Chair', 'Ergonomic office chair', 'Furniture', 3299.00, 5, 40, 'https://example.com/images/chair.jpg');
